stages:
 prepare:
  cmd: python src/train_test_split.py
  deps:
  - src/train_test_split.py
  outs:
  - assets/original_data
  - assets/train_test
 
 preprocessing:
  cmd: python src/preprocessing.py
  deps:
  - src/preprocessing.py
  - assets/train_test
  outs:
  - assets/processed
 
 feature_engineering:
  cmd: python src/feature_engineering.py
  deps:
  - src/feature_engineering.py
  - assets/processed
  outs:
  - assets/features

 model_training_evaluation:
  cmd: python src/model_training_evaluation.py
  deps:
  - src/model_training_evaluation.py
  - assets/features
  metrics:
  - assets/metrics.json